CREATE TABLESPACE RECURSOS_HUMANOS3
DATAFILE 'G:\Cursos\Udemy\Banco-de-Dados\ModuloOracle\systemRH_01.DBF'
SIZE 100M AUTOEXTEND
ON NEXT 100M
MAXSIZE 4096M;

ALTER TABLESPACE RECURSOS_HUMANOS
ADD DATAFILE 'G:\Cursos\Udemy\Banco-de-Dados\ModuloOracle\system\RH_02.DBF'
SIZE 200M AUTOEXTEND
ON NEXT 200M
MAXSIZE 4096M;

SELECT TABLESPACE_NAME, FILE_NAME FROM DBA_DATA_FILES;

-- SEQUENCE 
CREATE SEQUENCE SEQ_GERAL
START WITH 100
INCREMENT BY 10;

-- CRIANDO TABELA NA TABLESPACE
CREATE TABLE FUNCIONARIOS(
    IDFUNCIONARIO INT PRIMARY KEY,
    NOME VARCHAR2 (30) 
)TABLESPACE RECURSOS_HUMANOS;

INSERT INTO FUNCIONARIOS VALUES (SEQ_GERAL.NEXTVAL, 'JOAO');
INSERT INTO FUNCIONARIOS VALUES (SEQ_GERAL.NEXTVAL, 'CLARA');
INSERT INTO FUNCIONARIOS VALUES (SEQ_GERAL.NEXTVAL, 'LILIAN');

SELECT * FROM FUNCIONARIOS;

-- TRABALHANDO COM BACKUP
CREATE TABLESPACE MARKETING1 --CRIANDO TABLESPACE MKT
DATAFILE 'G:\Cursos\Udemy\Banco-de-Dados\ModuloOracle\system\MKT_01.DBF'
SIZE 100M AUTOEXTEND
ON NEXT 100M
MAXSIZE 4096M;

CREATE TABLE CAMPANHAS( -- CRIANDO TABELA NA TABLESPACE DO MKT
    IDCAMPANHA INT PRIMARY KEY,
    NOME VARCHAR2 (30) 
)TABLESPACE MARKETING1;

INSERT INTO CAMPANHAS VALUES (SEQ_GERAL.NEXTVAL, 'PRIMAVERA');
INSERT INTO CAMPANHAS VALUES (SEQ_GERAL.NEXTVAL, 'VERAO');
INSERT INTO CAMPANHAS VALUES (SEQ_GERAL.NEXTVAL, 'INVERNO');

SELECT * FROM FUNCIONARIOS;
SELECT * FROM CAMPANHAS;

/* MANUTENÇÃO DE BACKUP 
 COLOCANDO TABLESPACE OFFLINE */
 
ALTER TABLESPACE RECURSOS_HUMANOS OFFLINE; --OBS SEMPRE COPIAR OS ARQUIVOS 

/* APONTAR PARA O DICIONÁRIO DE DADOS */
ALTER TABLESPACE RECURSOS_HUMANOS
RENAME DATAFILE 'G:\Cursos\Udemy\Banco-de-Dados\ModuloOracle\RH_01.DBF'
TO G:\Cursos\Udemy\Banco-de-Dados\ModuloOracle\producao\RH_01.DBF';

ALTER TABLESPACE RECURSOS_HUMANOS
RENAME DATAFILE 'G:\Cursos\Udemy\Banco-de-Dados\ModuloOracle\RH_02.DBF'
TO 'G:\Cursos\Udemy\Banco-de-Dados\ModuloOracle\producao\RH_02.DBF';

/* TORNANDO TABLESPACE ONLINE */
ALTER TABLESPACE RECURSOS_HUMANOS ONLINE;

SELECT * FROM FUNCIONARIOS;
SELECT * FROM CAMPANHAS;

CREATE TABLE ALUNO(
    IDALUNO INT PRIMARY KEY,
    NOME VARCHAR2(30),
    EMAIL VARCHAR2(30),
    SALARIO NUMBER(10,2)
); 

CREATE SEQUENCE SEQ_EXEMPLO; 

/* LIGANDO SEQUENCE SEQ_EXAMPLE A TABELA ALUNO */

INSERT INTO ALUNO VALUES (SEQ_EXEMPLO.NEXTVAL,'JOAO','JOAO@GMAIL.COM',1000.00);
INSERT INTO ALUNO VALUES (SEQ_EXEMPLO.NEXTVAL,'CLARA','CLARA@GMAIL.COM',2000.00);
INSERT INTO ALUNO VALUES (SEQ_EXEMPLO.NEXTVAL,'CELIA','CELIA@GMAIL.COM',3000.00);

INSERT INTO ALUNO2 VALUES (SEQ_EXEMPLO.NEXTVAL,'JOAO','JOAO@GMAIL.COM',100.00);
INSERT INTO ALUNO2 VALUES (SEQ_EXEMPLO.NEXTVAL,'CLARA','CLARA@GMAIL.COM',200.00);
INSERT INTO ALUNO2 VALUES (SEQ_EXEMPLO.NEXTVAL,'CELIA','CELIA@GMAIL.COM',300.00)

/*ROWID E ROWNUM */
SELECT ROWID, IDALUNO,NOME, EMAIL FROM ALUNO;
SELECT ROWNUM, IDALUNO,NOME, EMAIL FROM ALUNO;
SELECT ROWID, ROWNUM, IDALUNO,NOME, EMAIL FROM ALUNO;
SELECT NOME, EMAIL FROM ALUNO WHERE ROWNUM > 2;

/* TRIGGER NO ORACLE */ 

/* procedure */

CREATE OR REPLACE PROCEDURE BONUS (P_IDALUNO ALUNO.IDALUNO%TYPE, P_PERCENT NUMBER)
AS 
    BEGIN
        UPDATE ALUNO SET SALARIO = SALARIO + (SALARIO * (P_PERCENT / 100))
        WHERE IDALUNO = P_IDALUNO;
    END;
    /

SELECT * FROM ALUNO;

CALL BONUS(3,10);

UPDATE ALUNO SET IDALUNO = 1
WHERE IDALUNO = 10;

/* TRIGGERS 
SIZE MAX 32K
NÃO EXECUTE DTL*/

/ * TRIGGER DE VALIDAÇÃO */

CREATE OR REPLACE TRIGGER CHECK_SALARIO
BEFORE INSERT OR UPDATE ON ALUNO
FOR EACH ROW
BEGIN
    IF :NEW.SALARIO > 2000 THEN
        RAISE_APPLICATION_ERROR (-20000, 'VALOR INCORRETO');
    END IF;
END;
/

SHOW ERROS;

SELECT TRIGGER_NAME, TRIGGER_BODY
FROM USER_TRIGGERS;

/ * TRIGGER DE EVENTOS */

CREATE TABLE AUDITORIA (
    DATA_LOGIN DATE,
    LOGIN VARCHAR2 (30)
);

CREATE OR REPLACE PROCEDURE LOGPROC IS
BEGIN
    INSERT INTO AUDITORIA (DATA_LOGIN,LOGIN)
    VALUES (SYSDATE,USER);
END LOGPROC;
/

SELECT SYSDATE AS DATA, 
USER AS USUARIOS
FROM DUAL;

CREATE OR REPLACE TRIGGER LOGTRIGGER
AFTER LOGON ON DATABASE
CALL LOGPROC
/

SELECT * FROM AUDITORIA;

/* FALHA DE LOGON */

CREATE OR REPLACE TRIGGER FALHA_LOGON
AFTER SERVERERROR
ON DATABASE
BEGIN
    IF (IS_SERVERERROR(1017)) THEN
    INSERT INTO AUDITORIA(DATA_LOGIN,LOGIN)
    VALUES (SYSDATE,'ORA-1017');
    END IF;    
END FALHA_LOGON;
/

/* TRIGGER DE DML */

CREATE TABLE USUARIO(
    ID INT,
    NOME VARCHAR2 (30)
);

CREATE TABLE BKP_USER(
    ID INT,
    NOME VARCHAR2 (30)
);

INSERT INTO USUARIO VALUES (1, 'JOAO');
INSERT INTO USUARIO VALUES (2, 'CLARA');
COMMIT;

SELECT * FROM USUARIO;

CREATE OR REPLACE TRIGGER LOG_USUARIO
BEFORE DELETE ON USUARIO
FOR EACH ROW
BEGIN
    INSERT INTO BKP_USER VALUES
    (:OLD.ID, :OLD.NOME);
END;
/
SELECT * FROM BKP_USER;

DELETE FROM USUARIO WHERE ID = 1;


delete from bkp_user;











