CREATE TABLESPACE RECURSOS_HUMANOS3
DATAFILE 'G:\Cursos\Udemy\Banco-de-Dados\ModuloOracle\systemRH_01.DBF'
SIZE 100M AUTOEXTEND
ON NEXT 100M
MAXSIZE 4096M;

ALTER TABLESPACE RECURSOS_HUMANOS
ADD DATAFILE 'G:\Cursos\Udemy\Banco-de-Dados\ModuloOracle\system\RH_02.DBF'
SIZE 200M AUTOEXTEND
ON NEXT 200M
MAXSIZE 4096M;

SELECT TABLESPACE_NAME, FILE_NAME FROM DBA_DATA_FILES;

-- SEQUENCE 
CREATE SEQUENCE SEQ_GERAL
START WITH 100
INCREMENT BY 10;

-- CRIANDO TABELA NA TABLESPACE
CREATE TABLE FUNCIONARIOS(
    IDFUNCIONARIO INT PRIMARY KEY,
    NOME VARCHAR2 (30) 
)TABLESPACE RECURSOS_HUMANOS;

INSERT INTO FUNCIONARIOS VALUES (SEQ_GERAL.NEXTVAL, 'JOAO');
INSERT INTO FUNCIONARIOS VALUES (SEQ_GERAL.NEXTVAL, 'CLARA');
INSERT INTO FUNCIONARIOS VALUES (SEQ_GERAL.NEXTVAL, 'LILIAN');

SELECT * FROM FUNCIONARIOS;

-- TRABALHANDO COM BACKUP
CREATE TABLESPACE MARKETING1 --CRIANDO TABLESPACE MKT
DATAFILE 'G:\Cursos\Udemy\Banco-de-Dados\ModuloOracle\system\MKT_01.DBF'
SIZE 100M AUTOEXTEND
ON NEXT 100M
MAXSIZE 4096M;

CREATE TABLE CAMPANHAS( -- CRIANDO TABELA NA TABLESPACE DO MKT
    IDCAMPANHA INT PRIMARY KEY,
    NOME VARCHAR2 (30) 
)TABLESPACE MARKETING1;

INSERT INTO CAMPANHAS VALUES (SEQ_GERAL.NEXTVAL, 'PRIMAVERA');
INSERT INTO CAMPANHAS VALUES (SEQ_GERAL.NEXTVAL, 'VERAO');
INSERT INTO CAMPANHAS VALUES (SEQ_GERAL.NEXTVAL, 'INVERNO');

SELECT * FROM FUNCIONARIOS;
SELECT * FROM CAMPANHAS;

/* MANUTENÇÃO DE BACKUP 
 COLOCANDO TABLESPACE OFFLINE */
 
ALTER TABLESPACE RECURSOS_HUMANOS OFFLINE; --OBS SEMPRE COPIAR OS ARQUIVOS 

/* APONTAR PARA O DICIONÁRIO DE DADOS */
ALTER TABLESPACE RECURSOS_HUMANOS
RENAME DATAFILE 'G:\Cursos\Udemy\Banco-de-Dados\ModuloOracle\RH_01.DBF'
TO G:\Cursos\Udemy\Banco-de-Dados\ModuloOracle\producao\RH_01.DBF';

ALTER TABLESPACE RECURSOS_HUMANOS
RENAME DATAFILE 'G:\Cursos\Udemy\Banco-de-Dados\ModuloOracle\RH_02.DBF'
TO 'G:\Cursos\Udemy\Banco-de-Dados\ModuloOracle\producao\RH_02.DBF';

/* TORNANDO TABLESPACE ONLINE */
ALTER TABLESPACE RECURSOS_HUMANOS ONLINE;

SELECT * FROM FUNCIONARIOS;
SELECT * FROM CAMPANHAS;

CREATE TABLE ALUNO(
    IDALUNO INT PRIMARY KEY,
    NOME VARCHAR2(30),
    EMAIL VARCHAR2(30),
    SALARIO NUMBER(10,2)
); 

CREATE SEQUENCE SEQ_EXEMPLO; 

/* LIGANDO SEQUENCE SEQ_EXAMPLE A TABELA ALUNO */

INSERT INTO ALUNO VALUES (SEQ_EXEMPLO.NEXTVAL,'JOAO','JOAO@GMAIL.COM',1000.00);
INSERT INTO ALUNO VALUES (SEQ_EXEMPLO.NEXTVAL,'CLARA','CLARA@GMAIL.COM',2000.00);
INSERT INTO ALUNO VALUES (SEQ_EXEMPLO.NEXTVAL,'CELIA','CELIA@GMAIL.COM',3000.00);

INSERT INTO ALUNO2 VALUES (SEQ_EXEMPLO.NEXTVAL,'JOAO','JOAO@GMAIL.COM',100.00);
INSERT INTO ALUNO2 VALUES (SEQ_EXEMPLO.NEXTVAL,'CLARA','CLARA@GMAIL.COM',200.00);
INSERT INTO ALUNO2 VALUES (SEQ_EXEMPLO.NEXTVAL,'CELIA','CELIA@GMAIL.COM',300.00)

/*ROWID E ROWNUM */
SELECT ROWID, IDALUNO,NOME, EMAIL FROM ALUNO;
SELECT ROWNUM, IDALUNO,NOME, EMAIL FROM ALUNO;
SELECT ROWID, ROWNUM, IDALUNO,NOME, EMAIL FROM ALUNO;
SELECT NOME, EMAIL FROM ALUNO WHERE ROWNUM > 2;

/* TRIGGER NO ORACLE */ 

/* procedure */

CREATE OR REPLACE PROCEDURE BONUS (P_IDALUNO ALUNO.IDALUNO%TYPE, P_PERCENT NUMBER)
AS 
    BEGIN
        UPDATE ALUNO SET SALARIO = SALARIO + (SALARIO * (P_PERCENT / 100))
        WHERE IDALUNO = P_IDALUNO;
    END;
    /

SELECT * FROM ALUNO;

CALL BONUS(3,10);

UPDATE ALUNO SET IDALUNO = 1
WHERE IDALUNO = 10;

/* TRIGGERS 
SIZE MAX 32K
NÃO EXECUTE DTL*/

/ * TRIGGER DE VALIDAÇÃO */

CREATE OR REPLACE TRIGGER CHECK_SALARIO
BEFORE INSERT OR UPDATE ON ALUNO
FOR EACH ROW
BEGIN
    IF :NEW.SALARIO > 2000 THEN
        RAISE_APPLICATION_ERROR (-20000, 'VALOR INCORRETO');
    END IF;
END;
/

SHOW ERROS;

SELECT TRIGGER_NAME, TRIGGER_BODY
FROM USER_TRIGGERS;

/ * TRIGGER DE EVENTOS */

CREATE TABLE AUDITORIA (
    DATA_LOGIN DATE,
    LOGIN VARCHAR2 (30)
);

CREATE OR REPLACE PROCEDURE LOGPROC IS
BEGIN
    INSERT INTO AUDITORIA (DATA_LOGIN,LOGIN)
    VALUES (SYSDATE,USER);
END LOGPROC;
/

SELECT SYSDATE AS DATA, 
USER AS USUARIOS
FROM DUAL;

CREATE OR REPLACE TRIGGER LOGTRIGGER
AFTER LOGON ON DATABASE
CALL LOGPROC
/

SELECT * FROM AUDITORIA;

/* FALHA DE LOGON */

CREATE OR REPLACE TRIGGER FALHA_LOGON
AFTER SERVERERROR
ON DATABASE
BEGIN
    IF (IS_SERVERERROR(1017)) THEN
    INSERT INTO AUDITORIA(DATA_LOGIN,LOGIN)
    VALUES (SYSDATE,'ORA-1017');
    END IF;    
END FALHA_LOGON;
/

/* TRIGGER DE DML */

CREATE TABLE USUARIO( -- table user 
    ID INT,
    NOME VARCHAR2 (30)
);

CREATE TABLE BKP_USER( -- backup for table user 
    ID INT,
    NOME VARCHAR2 (30)
);

INSERT INTO USUARIO VALUES (1, 'JOAO');
INSERT INTO USUARIO VALUES (2, 'CLARA');
COMMIT;

/* trigger backup delete from table user */  
CREATE OR REPLACE TRIGGER LOG_USUARIO
BEFORE DELETE ON USUARIO
FOR EACH ROW
BEGIN
    INSERT INTO BKP_USER VALUES (:OLD.ID, :OLD.NOME);
END;
/

SELECT * FROM USUARIO;
SELECT * FROM BKP_USER;

DELETE FROM USUARIO WHERE ID = 2;

delete from bkp_user;

/* VIEWS */

CREATE TABLE CLIENTE (
    IDCLIENTE INT PRIMARY KEY,
    NOME VARCHAR2(30),
    SEXO CHAR(1)
);    
    
INSERT INTO CLIENTE VALUES (1007, 'ALBERTO', 'M');

COMMIT;

SELECT * FROM CLIENTE;

CREATE OR REPLACE VIEW V_CLIENTE
AS
    SELECT IDCLIENTE, NOME, SEXO
    FROM CLIENTE;
    
INSERT INTO V_CLIENTE VALUES (1008, 'CLARA', 'F');   

SELECT * FROM CLIENTE;
SELECT * FROM V_CLIENTE;

CREATE OR REPLACE VIEW V_CLIENTE_RO
AS 
    SELECT IDCLIENTE, NOME, SEXO
    FROM CLIENTE
    WITH READ ONLY; -- SOMENTE LEITURA DA VIEW

INSERT INTO V_CLIENTE_RO VALUES (1009, 'MARIA', 'F'); 

-- VIEW DE JOIN 
CREATE OR REPLACE VIEW RELATORIO
AS
    SELECT NOME, SEXO, NUMERO
    FROM CLIENTE
    INNER JOIN TELEFONE
    ON IDCLIENTE = ID_CLIENTE;

-- USANDO CLAUSULA FORCE
CREATE OR REPLACE FORCE VIEW RELATORIO
AS
    SELECT NOME, SEXO, NUMERO
    FROM CLIENTE
    INNER JOIN TELEFONE
    ON IDCLIENTE = ID_CLIENTE;

CREATE TABLE TELEFONE(  --TABELA CRIADA DEPOIS DA FORCE VIEW 
    IDTELEFONE INT PRIMARY KEY,
    NUMERO VARCHAR (10),
    ID_CLIENTE INT
);

ALTER TABLE TELEFONE ADD CONSTRAINT FK_CLIENTE_TELEFONE
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (IDCLIENTE);

INSERT INTO TELEFONE VALUES (1,'12345678',1007);
COMMIT;

SELECT * FROM RELATORIO;

/* DEFERRABLE CONSTRAINT*/
CREATE TABLE FUNCIONARIO(
    IDFUNCIONARIO INT CONSTRAINT PK_FUNCIONARIO PRIMARY KEY,
    NOME VARCHAR2(100)
);

DROP TABLE TELEFONE;

CREATE TABLE TELEFONE(
    IDTELEFONE INT PRIMARY KEY,
    NUMERO VARCHAR2(10),
    ID_FUNCIONARIO INT
);    

ALTER TABLE TELEFONE ADD CONSTRAINT FK_TELEFONE
FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO;

INSERT INTO FUNCIONARIO VALUES (34,'MARCIO');
INSERT INTO TELEFONE VALUES (10,'87654321',1);

SELECT * FROM FUNCIONARIO;

SELECT * FROM TELEFONE;

/* VERIFICANDO CONSTRAINT */

SELECT CONSTRAINT_NAME, DEFERRABLE, DEFERRED
FROM USER_CONSTRAINTS WHERE TABLE_NAME IN('FUNCIONARIO','TELEFONE');

/* APAGANDO CONSTRAINT */
ALTER TABLE TELEFONE DROP CONSTRAINT FK_TELEFONE;

/* RECRIANDO A CONSTRAINT */
ALTER TABLE TELEFONE ADD CONSTRAINT FK_TELEFONE
FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO
DEFERRABLE; -- PODE SER ATRASADA NA VERIFICAÇÃO DE LIGAÇÃO DE TABELA

-- PODE CHECAR NA DTL
SELECT CONSTRAINT_NAME, DEFERRABLE AS ATRASADA, DEFERRED AS VERIFICACAO
FROM USER_CONSTRAINTS WHERE TABLE_NAME IN('FUNCIONARIO','TELEFONE');

INSERT INTO TELEFONE VALUES (4,'87654321',10);

/* MUDANDO PARA DTL*/
SET CONSTRAINTS ALL DEFERRED;

DELETE FROM TELEFONE WHERE ID_FUNCIONARIO = 10;



